version: 2
registries:
  npm-registry-npm-pkg-github-com-straitsit:
    type: npm-registry
    url: https://npm.pkg.github.com/straitsit
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_STRAITSIT_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.6
    - 10.1.1
  registries:
  - npm-registry-npm-pkg-github-com-straitsit
